// Generated by CoffeeScript 2.7.0
var hkex, match;

import {
  HKEXList,
  HKEXNew,
  reverse
} from '../index.js';

hkex = new HKEXNew();

match = function({typeDetail, type, title}) {
  var pattern;
  pattern = new RegExp(process.env.ALERT);
  return pattern.test(typeDetail) || pattern.test(type) || pattern.test(title);
};

(async function() {
  var i, ref, results;
  ref = reverse(hkex.iter());
  results = [];
  for await (i of ref) {
    if (match(i)) {
      results.push(console.log(i));
    } else {
      results.push(void 0);
    }
  }
  return results;
})();

(async function() {
  var ref, results, row;
  ref = (await HKEXList());
  results = [];
  for await (row of ref) {
    results.push(console.log(row));
  }
  return results;
})();
