// Generated by CoffeeScript 1.11.1
(function() {
  var HKEXNew, Promise, _, cheerio, http, params, row, table;

  _ = require('lodash');

  Promise = require('bluebird');

  http = Promise.promisifyAll(require('needle'));

  cheerio = require('cheerio');

  row = function(el) {
    var ret;
    ret = cheerio('td', el).toArray();
    return {
      date: cheerio('span', ret[0]).text(),
      code: cheerio('span', ret[1]).text(),
      name: cheerio('span', ret[2]).text(),
      doc: {
        type: cheerio('span:first-child', ret[3]).text(),
        name: cheerio('a', ret[3]).text(),
        link: cheerio('a', ret[3]).attr('href'),
        size: cheerio('span:last-child', ret[3]).text()
      }
    };
  };

  table = function(el) {
    var ret;
    return ret = cheerio('table#ctl00_gvMain tr:not([class])', el).toArray().map(row);
  };

  params = function(el, firstPage) {
    var keys, ret;
    if (firstPage == null) {
      firstPage = false;
    }
    keys = ['__VIEWSTATE', '__VIEWSTATEENCRYPTED'];
    if (firstPage) {
      keys = keys.concat(['ctl00$txt_today', 'ctl00$hfStatus', 'ctl00$hfAlert', 'ctl00$txt_stock_code', 'ctl00$txt_stock_name', 'ctl00$rdo_SelectDocType', 'ctl00$sel_tier_1', 'ctl00$sel_DocTypePrior2006', 'ctl00$sel_tier_2_group', 'ctl00$sel_tier_2', 'ctl00$ddlTierTwo', 'ctl00$ddlTierTwoGroup', 'ctl00$txtKeyWord', 'ctl00$rdo_SelectDateOfRelease', 'ctl00$sel_DateOfReleaseFrom_d', 'ctl00$sel_DateOfReleaseFrom_m', 'ctl00$sel_DateOfReleaseFrom_y', 'ctl00$sel_DateOfReleaseTo_d', 'ctl00$sel_DateOfReleaseTo_m', 'ctl00$sel_DateOfReleaseTo_y', 'ctl00$sel_defaultDateRange', 'ctl00$rdo_SelectSortBy']);
    }
    ret = {};
    _.map(keys, function(key) {
      var selector;
      selector = key.match(/sel_|ddl/) ? "select" : "input";
      return ret[key] = cheerio(selector + "[name='" + key + "']", el).val();
    });
    if (!firstPage) {
      ret['ctl00$btnNext.x'] = 1;
      ret['ctl00$btnNext.y'] = 1;
    }
    return ret;
  };

  HKEXNew = (function() {
    HKEXNew.$urlRoot = {
      en: 'http://www.hkexnews.hk/listedco/listconews/advancedsearch/search_active_main.aspx',
      ch: 'http://www.hkexnews.hk/listedco/listconews/advancedsearch/search_active_main_c.aspx'
    };

    HKEXNew.prototype.models = [];

    function HKEXNew(params1, lang1) {
      this.params = params1;
      this.lang = lang1 != null ? lang1 : 'en';
      return;
    }

    HKEXNew.prototype.$fetch = function() {
      return http.postAsync(HKEXNew.$urlRoot[this.lang], this.params).then((function(_this) {
        return function(res) {
          return _this.$parse(res);
        };
      })(this));
    };

    HKEXNew.prototype.$parse = function(res) {
      this.params = params(res.body);
      _.each(table(res.body), (function(_this) {
        return function(model) {
          return _this.models.push(model);
        };
      })(this));
      return this;
    };

    return HKEXNew;

  })();

  module.exports = function(lang) {
    if (lang == null) {
      lang = 'en';
    }
    return http.getAsync(HKEXNew.$urlRoot[lang]).then(function(res) {
      return new HKEXNew(params(res.body, true), lang);
    });
  };

}).call(this);
